######### Timezone

timezone: Asia/Taipei


######## Oh-My-Zsh

users:
  - username: zx1986


######### Nginx

nginx_remove_default_vhost: true

nginx_vhosts:
  - listen: "80 default_server"
    server_name: "_"
    root: "/var/www/html/phpday.tw/public"
    index: "index.php index.html index.htm"
    state: "present"
    filename: "phpday.tw.conf"
    extra_parameters: |
      location / {
        try_files $uri $uri/ /index.php?$query_string;
      }
      location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
      }


######### PHP

# Set this to false if you're not using PHP with Apache/Nginx/etc.
php_enable_webserver: true

# PHP-FPM configuration.
php_webserver_daemon: "nginx"
php_enable_php_fpm: true
php_fpm_listen: "127.0.0.1:9000"
php_fpm_listen_allowed_clients: "127.0.0.1"
php_fpm_pm_max_children: 50
php_fpm_pm_start_servers: 5
php_fpm_pm_min_spare_servers: 5
php_fpm_pm_max_spare_servers: 5

php_expose_php: "On"
php_short_open_tag: "Off"
php_allow_url_fopen: "On"

php_memory_limit: "256M"
php_max_execution_time: "60"
php_max_input_time: "60"
php_max_input_vars: "1000"

php_file_uploads: "On"
php_upload_max_filesize: "64M"
php_max_file_uploads: "20"
php_post_max_size: "32M"
php_date_timezone: "Asia/Taipei"

php_error_reporting: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
php_display_errors: "Off"
php_display_startup_errors: "Off"


######### MySQL

mysql_packages:
  - mariadb-client
  - mariadb-server
  - python-mysqldb

mysql_root_password: root@phpday.tw

mysql_databases:
  - name: phpday
    encoding: utf8
    collation: utf8_general_ci

mysql_users:
  - name: phpday
    host: "%"
    password: user@phpday.tw
    priv: "phpday.*:ALL"
